#!/usr/bin/env python3
"""Rebuild the root README.md from scripts/targets.json.

The root README is GENERATED - do not hand-edit it. Edit targets.json (or the
per-convention pages), then run this script. Conventions are grouped by
category in the declared order; manual_readme conventions appear as normal
index rows (their detailed page is hand-written).

Usage:
    python scripts/build_readme.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGETS_PATH = os.path.join(ROOT, "scripts", "targets.json")
README_PATH = os.path.join(ROOT, "README.md")
CATEGORIES_DIR = os.path.join(ROOT, "categories")

CATEGORY_SLUGS = {
    "Instruction & context": "instruction-context",
    "Memory & state": "memory-state",
    "Spec-driven development": "spec-driven-development",
    "Skills & prompt assets": "skills-prompt-assets",
    "Tooling & connections": "tooling-connections",
    "Rules & ignore files": "rules-ignore-files",
    "Design": "design",
    "Web & discoverability": "web-discoverability",
    "Agent-web trust": "agent-web-trust",
    "Identity & protocols": "identity-protocols",
    "Proposed namespace": "proposed-namespace",
}


def anchor(text):
    """Approximate GitHub's heading-anchor algorithm."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\s-]", "", a)
    a = a.replace(" ", "-")
    return a


def spec_link(spec, text="spec ↗"):
    if not spec:
        return "-"
    href = spec if spec.startswith("http") else f"https://{spec}"
    return f"[{text}]({href})"


def files_cell(conv):
    parts = []
    for f in conv["files"]:
        if f.get("kind") == "pattern":
            parts.append(f"`{f['name']}` _(pattern)_")
        else:
            parts.append(f"`{f['name']}`")
    return " ".join(parts)


def category_slug(category):
    """Stable filenames for generated category index pages."""
    if category in CATEGORY_SLUGS:
        return CATEGORY_SLUGS[category]
    slug = anchor(category).replace("--", "-")
    return slug or "category"


def category_page_path(category):
    return os.path.join(CATEGORIES_DIR, f"{category_slug(category)}.md")


def convention_row(slug, conv):
    return (
        f"| {conv['maturity']} "
        f"| [{conv['name']}](../conventions/{slug}/) "
        f"| {files_cell(conv)} "
        f"| {conv['read_by']} "
        f"| {spec_link(conv['spec'])} |"
    )


def root_convention_row(slug, conv):
    return (
        f"| {conv['maturity']} "
        f"| [{conv['name']}](conventions/{slug}/) "
        f"| {files_cell(conv)} "
        f"| {conv['read_by']} "
        f"| {spec_link(conv['spec'])} |"
    )


REPO = "ItamarZand88/awesome-agent-conventions"

HEADER = """<!-- GENERATED by scripts/build_readme.py - do not hand-edit. -->
<!-- Edit scripts/targets.json (or per-convention pages), then re-run the script. -->

<p align="center">
  <img src="assets/hero.png" alt="awesome-agent-conventions - the real files AI agents read, write, and act on" width="100%">
</p>

# awesome-agent-conventions

<p align="center">
  <a href="https://awesome.re"><img src="https://awesome.re/badge.svg" alt="Awesome"></a>
  <a href="https://github.com/{repo}/actions/workflows/verify.yml"><img src="https://github.com/{repo}/actions/workflows/verify.yml/badge.svg" alt="verify"></a>
  <a href="LICENSE"><img src="https://img.shields.io/badge/license-MIT-blue.svg" alt="License: MIT"></a>
</p>

**The files AI coding agents actually read - `AGENTS.md`, `CLAUDE.md`, `.cursorrules`, `SKILL.md`, `llms.txt`, and more - collected in one place, with a real example of each.**

{stat}

Every AI tool invented its own files for steering an agent: what to build and
test, which rules to follow, what tools to connect, how to remember things
between sessions. They're scattered across docs and easy to confuse. This repo
gathers them in one place and answers three questions for each one:

- **What is it, and which agent reads it?** A one-line summary, the tools that
  consume it, and where the file lives.
- **What does a real one look like?** Every entry links a folder of actual
  example files pulled from public repos by a script - so you copy a working
  file, not a description of one.
- **Should I trust it?** Each entry is labelled by how widely it's *actually*
  adopted, so a proposed idea never sits beside a settled standard as its equal.
"""

FILTER = """## What counts

A file qualifies only if it is an **agent convention file**: it exists for an AI
agent to **read, write, or act on**. Any extension - `.md`, `.txt`, `.prompty`,
`.json`, dotfiles. Files written for humans (`README.md`, `CONTRIBUTING.md`,
`SECURITY.md`, `CHANGELOG.md`) are **out**.
"""

TIERS = """## Maturity tiers

Every entry carries one tier, with evidence. Honest labelling is the whole point -
a proposed idea is never shown beside an adopted standard as if they were equal.

| Badge | Tier | Meaning |
| --- | --- | --- |
| 🟢 | **Adopted** | In production across multiple tools or teams. |
| 🟠 | **Emerging** | A real published spec from a real org, but early / limited adoption. |
| 🔵 | **Proposed** | A published concept with no demonstrated adoption (often one author staking a namespace). |
"""

HOW = """## How the examples stay real

Example files are never hand-written - an extractor fetches them from public
sources and stamps each with a line-1 provenance comment. The examples remain
under their upstream owners' licenses and terms; see
[THIRD_PARTY_EXAMPLES.md](THIRD_PARTY_EXAMPLES.md) before reusing them. To
refresh everything:

```bash
pip install -r scripts/requirements.txt
python scripts/extract.py          # fetch real files + rebuild each convention's README
python scripts/build_readme.py     # rebuild this README from scripts/targets.json
```

Re-running is idempotent and never crashes on a missing source - a dead target
just prints a `miss` and is skipped. Examples are representative samples: any
file over 256 KB (e.g. a multi-MB `llms-full.txt`) is truncated with a marker
pointing back to the full source. `scripts/targets.json` is the single source of
truth; edit it and re-run both scripts.

Shortcut targets are available in the [Makefile](Makefile):

```bash
make verify          # schema + generated files + example provenance + links
make extract         # refetch public examples and rebuild generated docs
make license-report  # summarize upstream licenses for vendored examples
```

Every link is held to its promise by CI: a [GitHub Action](.github/workflows/verify.yml)
re-checks that the generated files are in sync with `targets.json` and that every
spec, example, and instance URL still resolves - on each pull request and weekly.
Run the same check locally with `python scripts/check_links.py`.
"""

CONTRIB = """## Contributing

Read [CONTRIBUTING.md](CONTRIBUTING.md). In short: an entry must pass the filter
above and carry an evidenced maturity tier. Add your source to
`scripts/targets.json`, run the two scripts, and open a PR - don't hand-write
example files.

Before proposing adjacent standards, check [WATCHLIST.md](WATCHLIST.md). Project
direction lives in [ROADMAP.md](ROADMAP.md), and the one-time public release
checklist lives in [OPEN_SOURCE_LAUNCH_CHECKLIST.md](OPEN_SOURCE_LAUNCH_CHECKLIST.md).

## License

The curation, scripts, and original prose in this repository are
[MIT](LICENSE). Vendored example files remain under their upstream owners'
licenses and terms; see [THIRD_PARTY_EXAMPLES.md](THIRD_PARTY_EXAMPLES.md).
"""


def build():
    with open(TARGETS_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    categories = data["categories"]
    conventions = data["conventions"]

    by_cat = {c: [] for c in categories}
    for slug, conv in conventions.items():
        by_cat.setdefault(conv["category"], []).append((slug, conv))

    n_conv = len(conventions)
    n_cat = sum(1 for cat in categories if by_cat.get(cat))
    stat = (
        f"**{n_conv} conventions across {n_cat} categories** - from the "
        "instruction files every coding agent reads to the discovery files the "
        "agent web is still inventing."
    )

    out = [HEADER.format(repo=REPO, stat=stat), FILTER, TIERS]

    # Table of contents
    out.append("## Contents\n")
    toc = []
    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        cat_page = f"categories/{category_slug(cat)}.md"
        toc.append(f"- [{cat}](#{anchor(cat)}) · [category page]({cat_page})")
        for slug, conv in entries:
            toc.append(f"  - {conv['maturity']} [{conv['name']}](conventions/{slug}/)")
    out.append("\n".join(toc) + "\n")

    # Per-category sections
    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        section = [f"## {cat}\n"]
        section.append(f"Standalone page: [categories/{category_slug(cat)}.md](categories/{category_slug(cat)}.md)")
        section.append("")
        section.append("| | Convention | Files | Read by | Spec |")
        section.append("| --- | --- | --- | --- | --- |")
        for slug, conv in entries:
            section.append(root_convention_row(slug, conv))
        section.append("")
        for slug, conv in entries:
            section.append(
                f"- **[{conv['name']}](conventions/{slug}/)** - {conv['summary']}"
            )
        out.append("\n".join(section) + "\n")

    out.append(HOW)
    out.append(CONTRIB)

    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {os.path.relpath(README_PATH, ROOT)}")

    build_category_pages(categories, by_cat)


def build_category_pages(categories, by_cat):
    os.makedirs(CATEGORIES_DIR, exist_ok=True)
    expected = set()

    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue

        path = category_page_path(cat)
        expected.add(os.path.basename(path))
        out = [
            "<!-- GENERATED by scripts/build_readme.py - do not hand-edit. -->",
            "",
            f"# {cat}",
            "",
            "[Back to README](../README.md)",
            "",
            "| | Convention | Files | Read by | Spec |",
            "| --- | --- | --- | --- | --- |",
        ]
        for slug, conv in entries:
            out.append(convention_row(slug, conv))
        out.append("")
        for slug, conv in entries:
            out.append(f"## [{conv['name']}](../conventions/{slug}/)")
            out.append("")
            out.append(conv["summary"])
            out.append("")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(out))
        print(f"wrote {os.path.relpath(path, ROOT)}")

    for name in os.listdir(CATEGORIES_DIR):
        if name.endswith(".md") and name not in expected:
            os.remove(os.path.join(CATEGORIES_DIR, name))
            print(f"removed {os.path.join('categories', name)}")


if __name__ == "__main__":
    build()
