#!/usr/bin/env python3
"""Rebuild the root README.md from scripts/targets.json.

The root README is GENERATED — do not hand-edit it. Edit targets.json (or the
per-convention pages), then run this script. Conventions are grouped by
category in the declared order; manual_readme conventions appear as normal
index rows (their detailed page is hand-written).

Usage:
    python scripts/build_readme.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGETS_PATH = os.path.join(ROOT, "scripts", "targets.json")
README_PATH = os.path.join(ROOT, "README.md")


def anchor(text):
    """Approximate GitHub's heading-anchor algorithm."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\s-]", "", a)
    a = a.replace(" ", "-")
    return a


def spec_link(spec, text="spec ↗"):
    if not spec:
        return "—"
    href = spec if spec.startswith("http") else f"https://{spec}"
    return f"[{text}]({href})"


def files_cell(conv):
    return " ".join(f"`{f['name']}`" for f in conv["files"])


HEADER = """<!-- GENERATED by scripts/build_readme.py — do not hand-edit. -->
<!-- Edit scripts/targets.json (or per-convention pages), then re-run the script. -->

# awesome-agent-conventions

**A collection of the real files AI agents read, write, and act on — extracted from production, organized by purpose, and labelled by how widely they're actually adopted.**

Not a glossary. Every entry links to a folder of *real files* pulled from public
sources by an extractor — so you can fork this and copy the actual artifact, not
a description of one.
"""

FILTER = """## What counts

A file qualifies only if it is an **agent convention file**: it exists for an AI
agent to **read, write, or act on**. Any extension — `.md`, `.txt`, `.prompty`,
`.json`, dotfiles. Files written for humans (`README.md`, `CONTRIBUTING.md`,
`SECURITY.md`, `CHANGELOG.md`) are **out**.
"""

TIERS = """## Maturity tiers

Every entry carries one tier, with evidence. Honest labelling is the whole point —
a proposed idea is never shown beside an adopted standard as if they were equal.

| Badge | Tier | Meaning |
| --- | --- | --- |
| 🟢 | **Adopted** | In production across multiple tools or teams. |
| 🟡 | **Emerging** | A real published spec from a real org, but early / limited adoption. |
| 🔵 | **Proposed** | A published concept with no demonstrated adoption (often one author staking a namespace). |
"""

HOW = """## How the examples stay real

Example files are never hand-written — an extractor fetches them from public
sources and stamps each with a line-1 provenance comment. To refresh everything:

```bash
pip install -r scripts/requirements.txt
python scripts/extract.py          # fetch real files + rebuild each convention's README
python scripts/build_readme.py     # rebuild this README from scripts/targets.json
```

Re-running is idempotent and never crashes on a missing source — a dead target
just prints a `miss` and is skipped. Examples are representative samples: any
file over 256 KB (e.g. a multi-MB `llms-full.txt`) is truncated with a marker
pointing back to the full source. `scripts/targets.json` is the single source of
truth; edit it and re-run both scripts.
"""

CONTRIB = """## Contributing

Read [CONTRIBUTING.md](CONTRIBUTING.md). In short: an entry must pass the filter
above and carry an evidenced maturity tier. Add your source to
`scripts/targets.json`, run the two scripts, and open a PR — don't hand-write
example files.

## License

[MIT](LICENSE).
"""


def build():
    with open(TARGETS_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    categories = data["categories"]
    conventions = data["conventions"]

    by_cat = {c: [] for c in categories}
    for slug, conv in conventions.items():
        by_cat.setdefault(conv["category"], []).append((slug, conv))

    out = [HEADER, FILTER, TIERS]

    # Table of contents
    out.append("## Contents\n")
    toc = []
    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        toc.append(f"- [{cat}](#{anchor(cat)})")
        for slug, conv in entries:
            toc.append(f"  - {conv['maturity']} [{conv['name']}](conventions/{slug}/)")
    out.append("\n".join(toc) + "\n")

    # Per-category sections
    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        section = [f"## {cat}\n"]
        section.append("| | Convention | Files | Read by | Spec |")
        section.append("| --- | --- | --- | --- | --- |")
        for slug, conv in entries:
            section.append(
                f"| {conv['maturity']} "
                f"| [{conv['name']}](conventions/{slug}/) "
                f"| {files_cell(conv)} "
                f"| {conv['read_by']} "
                f"| {spec_link(conv['spec'])} |"
            )
        section.append("")
        for slug, conv in entries:
            section.append(
                f"- **[{conv['name']}](conventions/{slug}/)** — {conv['summary']}"
            )
        out.append("\n".join(section) + "\n")

    out.append(HOW)
    out.append(CONTRIB)

    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {os.path.relpath(README_PATH, ROOT)}")


if __name__ == "__main__":
    build()
