#!/usr/bin/env python3
"""Rebuild the root README.md from catalog metadata.

The root README is GENERATED - do not hand-edit it. Edit `scripts/targets.json`
for non-migrated conventions, or local convention metadata for complete pilot
entries such as `skill-md`, then run this script. Conventions are grouped by
category in the declared order; manual_readme conventions appear as normal
index rows (their detailed page is hand-written).

Usage:
    python scripts/build_readme.py
"""
import json
import os
import re

from catalog import has_complete_local_metadata, load_local_metadata, overlay_local_convention

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TARGETS_PATH = os.path.join(ROOT, "scripts", "targets.json")
README_PATH = os.path.join(ROOT, "README.md")
CATEGORIES_DIR = os.path.join(ROOT, "categories")

CATEGORY_SLUGS = {
    "Instruction & context": "instruction-context",
    "Memory & state": "memory-state",
    "Spec-driven development": "spec-driven-development",
    "Skills & prompt assets": "skills-prompt-assets",
    "Tooling & connections": "tooling-connections",
    "Rules & ignore files": "rules-ignore-files",
    "Design": "design",
    "Web & discoverability": "web-discoverability",
    "Agent-web trust": "agent-web-trust",
    "Identity & protocols": "identity-protocols",
    "Proposed namespace": "proposed-namespace",
}


def anchor(text):
    """Approximate GitHub's heading-anchor algorithm."""
    a = text.strip().lower()
    a = re.sub(r"[^\w\s-]", "", a)
    a = a.replace(" ", "-")
    return a


def spec_link(spec, text="spec ↗"):
    if not spec:
        return "-"
    href = spec if spec.startswith("http") else f"https://{spec}"
    return f"[{text}]({href})"


def files_cell(conv):
    parts = []
    for f in conv["files"]:
        if f.get("kind") == "pattern":
            parts.append(f"`{f['name']}` _(pattern)_")
        else:
            parts.append(f"`{f['name']}`")
    return " ".join(parts)


def category_slug(category):
    """Stable filenames for generated category index pages."""
    if category in CATEGORY_SLUGS:
        return CATEGORY_SLUGS[category]
    slug = anchor(category).replace("--", "-")
    return slug or "category"


def category_page_path(category):
    return os.path.join(CATEGORIES_DIR, f"{category_slug(category)}.md")


def convention_row(slug, conv):
    return (
        f"| {conv['maturity']} "
        f"| [{conv['name']}](../conventions/{slug}/) "
        f"| {files_cell(conv)} "
        f"| {conv['read_by']} "
        f"| {spec_link(conv['spec'])} |"
    )


def root_convention_row(slug, conv):
    return (
        f"| {conv['maturity']} "
        f"| [{conv['name']}](conventions/{slug}/) "
        f"| {files_cell(conv)} "
        f"| {conv['read_by']} "
        f"| {spec_link(conv['spec'])} |"
    )


REPO = "ItamarZand88/awesome-agent-conventions"

HEADER = """<!-- GENERATED by scripts/build_readme.py - do not hand-edit. -->
<!-- Edit scripts/targets.json (or per-convention pages), then re-run the script. -->

<p align="center">
  <img src="assets/hero.png" alt="Awesome Agent Conventions - convention files for AI agents" width="100%">
</p>

# Awesome Agent Conventions

<p align="center">
  <a href="https://awesome.re"><img src="https://awesome.re/badge.svg" alt="Awesome"></a>
  <a href="https://github.com/{repo}/actions/workflows/verify.yml"><img src="https://github.com/{repo}/actions/workflows/verify.yml/badge.svg" alt="verify"></a>
  <a href="LICENSE"><img src="https://img.shields.io/badge/license-MIT-blue.svg" alt="License: MIT"></a>
</p>

**A curated field guide to the convention files AI agents read, write, and act on.**

{stat}

Agent tools increasingly rely on plain files in a repository or website root:
instructions, memory, rules, tool connections, prompt assets, discovery
metadata, and protocol hints. The names are easy to mix up, and the adoption
levels vary a lot.

This repo keeps the map practical:

- **Know what a file is for.** Each entry names the convention, usual filename,
  primary readers, and spec or source.
- **Study real examples.** Examples are fetched from public repositories by
  script, with provenance kept at the top of each file.
- **Separate practice from proposal.** Maturity labels show what is widely used,
  what is early, and what is still only proposed.
"""

FILTER = """## What counts

This list is intentionally narrow. A file belongs here when it is a convention
for agent behavior or agent-readable metadata: instructions, memory, skills,
rules, tool config, prompt assets, or web-discovery hints.

Any file type can qualify - `.md`, `.txt`, `.prompty`, `.json`, dotfiles, or a
directory pattern. Human-first project docs such as `README.md`,
`CONTRIBUTING.md`, `SECURITY.md`, and `CHANGELOG.md` stay out unless the file has
become an agent convention in its own right.
"""

TIERS = """## Maturity tiers

The badge is a claim about adoption, not quality. It keeps a proven convention
from being presented the same way as a new idea.

| Badge | Tier | Meaning |
| --- | --- | --- |
| 🟢 | **Adopted** | Used in production by multiple tools, projects, or teams. |
| 🟠 | **Emerging** | Published by a real organization, but still early or limited in adoption. |
| 🔵 | **Proposed** | Publicly described, but without clear adoption beyond the proposal. |
"""

HOW = """## Maintaining examples

Example files are fetched, not invented. The extractor pulls them from public
sources, stores them under `conventions/<slug>/examples/<source>/<filename>`,
and adds a line-1 provenance comment. The examples remain under their upstream
owners' licenses and terms; see
[THIRD_PARTY_EXAMPLES.md](THIRD_PARTY_EXAMPLES.md) before reusing them.

To refresh everything:

```bash
pip install -r scripts/requirements.txt
python scripts/extract.py          # fetch real files + rebuild each convention's README
python scripts/build_readme.py     # rebuild this README from scripts/targets.json
```

Re-running is idempotent. A missing target prints a `miss` and is skipped.
Examples are representative samples: any file over 256 KB (for example, a
multi-MB `llms-full.txt`) is truncated with a marker pointing back to the full
source. `scripts/targets.json` remains the source of truth for conventions that
have not been migrated yet; the `skill-md` pilot uses local convention metadata
instead. Edit the relevant source and re-run both scripts.

Shortcut targets are available in the [Makefile](Makefile):

```bash
make verify          # schema + generated files + example provenance + links
make extract         # refetch public examples and rebuild generated docs
make license-report  # summarize upstream licenses for vendored examples
```

CI keeps the generated files and links honest. The
[verify workflow](.github/workflows/verify.yml) checks that generated docs match
catalog metadata and migrated local metadata, and that every spec, example, and
instance URL still resolves on each pull request and weekly. Run the same link
check locally with
`python scripts/check_links.py`.
"""

CONTRIB = """## Contributing

Read [CONTRIBUTING.md](CONTRIBUTING.md). In short: an entry must pass the filter
above and carry evidence for its maturity tier. Add sources to
`scripts/targets.json` for non-migrated conventions, run the scripts, and open
a PR. The `skill-md` pilot uses local convention metadata instead. Do not
hand-write example files.

Before proposing adjacent standards, check [WATCHLIST.md](WATCHLIST.md). Project
direction lives in [ROADMAP.md](ROADMAP.md).

## License

The curation, scripts, and original prose in this repository are
[MIT](LICENSE). Vendored example files remain under their upstream owners'
licenses and terms; see [THIRD_PARTY_EXAMPLES.md](THIRD_PARTY_EXAMPLES.md).
"""


def build():
    with open(TARGETS_PATH, encoding="utf-8") as fh:
        data = json.load(fh)
    categories = data["categories"]
    conventions = {}
    for slug, conv in data["conventions"].items():
        if has_complete_local_metadata(slug):
            local_convention, local_sources = load_local_metadata(slug)
            conventions[slug] = overlay_local_convention(conv, local_convention, local_sources)
        else:
            conventions[slug] = conv

    by_cat = {c: [] for c in categories}
    for slug, conv in conventions.items():
        by_cat.setdefault(conv["category"], []).append((slug, conv))

    n_conv = len(conventions)
    n_cat = sum(1 for cat in categories if by_cat.get(cat))
    stat = (
        f"**{n_conv} conventions across {n_cat} categories.** From common "
        "project instruction files to newer agent-web discovery and trust formats."
    )

    out = [HEADER.format(repo=REPO, stat=stat)]

    # Table of contents
    out.append("## Contents\n")
    toc = []
    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        cat_page = f"categories/{category_slug(cat)}.md"
        toc.append(f"- [{cat}](#{anchor(cat)}) · [category page]({cat_page})")
        for slug, conv in entries:
            toc.append(f"  - {conv['maturity']} [{conv['name']}](conventions/{slug}/)")
    out.append("\n".join(toc) + "\n")
    out.append(FILTER)
    out.append(TIERS)

    # Per-category sections
    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue
        section = [f"## {cat}\n"]
        section.append(f"Standalone page: [categories/{category_slug(cat)}.md](categories/{category_slug(cat)}.md)")
        section.append("")
        section.append("| | Convention | Files | Read by | Spec |")
        section.append("| --- | --- | --- | --- | --- |")
        for slug, conv in entries:
            section.append(root_convention_row(slug, conv))
        section.append("")
        for slug, conv in entries:
            section.append(
                f"- **[{conv['name']}](conventions/{slug}/)** - {conv['summary']}"
            )
        out.append("\n".join(section) + "\n")

    out.append(HOW)
    out.append(CONTRIB)

    with open(README_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {os.path.relpath(README_PATH, ROOT)}")

    build_category_pages(categories, by_cat)


def build_category_pages(categories, by_cat):
    os.makedirs(CATEGORIES_DIR, exist_ok=True)
    expected = set()

    for cat in categories:
        entries = by_cat.get(cat, [])
        if not entries:
            continue

        path = category_page_path(cat)
        expected.add(os.path.basename(path))
        out = [
            "<!-- GENERATED by scripts/build_readme.py - do not hand-edit. -->",
            "",
            f"# {cat}",
            "",
            "[Back to README](../README.md)",
            "",
            "| | Convention | Files | Read by | Spec |",
            "| --- | --- | --- | --- | --- |",
        ]
        for slug, conv in entries:
            out.append(convention_row(slug, conv))
        out.append("")
        for slug, conv in entries:
            out.append(f"## [{conv['name']}](../conventions/{slug}/)")
            out.append("")
            out.append(conv["summary"])
            out.append("")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(out))
        print(f"wrote {os.path.relpath(path, ROOT)}")

    for name in os.listdir(CATEGORIES_DIR):
        if name.endswith(".md") and name not in expected:
            os.remove(os.path.join(CATEGORIES_DIR, name))
            print(f"removed {os.path.join('categories', name)}")


if __name__ == "__main__":
    build()
